GROQ_API_KEY = "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"
TAVILY_API_KEY = "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"
SERPER_API_KEY = "cf097d5764f7e7ef187519cf5fa5e145ff73877a"
HF_TOKEN = "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"